-- Replace placeholders before running:
--   __DB_NAME__
--   __APP_SP_CLIENT_ID__

CREATE ROLE "__APP_SP_CLIENT_ID__" LOGIN;

GRANT CONNECT ON DATABASE "__DB_NAME__" TO "__APP_SP_CLIENT_ID__";
GRANT USAGE ON SCHEMA public TO "__APP_SP_CLIENT_ID__";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "__APP_SP_CLIENT_ID__";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "__APP_SP_CLIENT_ID__";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "__APP_SP_CLIENT_ID__";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO "__APP_SP_CLIENT_ID__";
